### ISSUE TITLE
The audio stops when opening a new Browser window

### ISSUE THREAD

**Issue by siddhugolu** [generative-music/generative.fm#74] opened 2019-04-01 09:04 UTC
The audio stops whenever I open a new browser window (Firefox) on my laptop, which has Windows 8 operating system.

**Comment by metalex9** [comment] 2019-04-01 21:54
That's a bummer, I will test this and see what I can do.

**Comment by metalex9** [comment] 2019-04-02 22:48
@siddhugolu I was not able to reproduce this in Firefox 66.0.2 (64-bit) on Windows 10. Which version of Firefox are you using?

**Comment by siddhugolu** [comment] 2019-04-03 09:19
@metalex9 That's strange. I'm using the same system (Firefox 66.0.2, Windows 10). To clarify my issue, the audio symbols remain as it is (as in the sound symbol as well as the play button doesn't change their state), but the audio stops playing through the speakers/earphones. I have to stop the audio and then hit play again to resume. I'm attaching a screenshot of the said behaviour for clarification. While taking this screenshot, I'm not able to listen to the audio. I hope I've made the issue clear, rather than confusing you more.
![Screenshot_2019-04-03 Generative fm](https://user-images.githubusercontent.com/9106868/55467577-1e93e900-55f1-11e9-8c29-72a04b649cb5.png)

**Comment by metalex9** [comment] 2019-04-03 15:59
I think I understand it but I'm not sure what's going on. How are you opening new windows and producing the issue?

**Comment by siddhugolu** [comment] 2019-04-05 17:51
The issue occurs when I'm opening a new window of the browser with the keyboard shortcut (Ctrl + Shift + N in this instance).

**Comment by metalex9** [comment] 2019-04-06 05:50
I tried reproducing this in Firefox 66.0.2 64-bit on Windows 10 by using Ctrl + Shift + N and Ctrl + N to open a new window, but the audio still worked as expected. I'm gonna close this for now since there's not much I can do. I'll reopen if we can figure out how to reproduce it reliably. Sorry!

**Closed by metalex9** 2019-04-06 05:50 UTC
