### ISSUE TITLE
Music not playing in Chrome

### ISSUE THREAD

**Issue by arturhenryy** [generative-music/generative.fm#65] opened 2019-03-27 13:41 UTC
<img width="639" alt="Bildschirmfoto 2019-03-27 um 14 39 46" src="https://user-images.githubusercontent.com/45144968/55080298-3bcf3180-509e-11e9-9260-b6e965b5e936.png">

if i click on a piece the loading indicator keeps spinning and no sound is playing.
appeared under chrome 73

**Comment by arturhenryy** [comment] 2019-03-27 13:42
this usually seems like an autoplay issue, but it seems weird because it also is not working once i interacted with the page with pressing play

**Comment by metalex9** [comment] 2019-03-27 15:57
The warnings you're seeing are probably a red herring. I also get those before I interact with the page even though the app makes no attempts to play audio until you click. I think maybe Tone.js might try to autostart the context or perhaps it's because I create and connect some volume nodes on load. I do have a click handler which properly starts the audio context and abides by the autoplay policy. Since you said the loading icon kept spinning, I'm going to guess it just took a long time to load the audio files. They aren't actually fetched until you click play, and some pieces can queue up quite a large list of them. The loading icon will spin until they're all loaded, and only then will it play audio. Do you happen to remember which piece(s) you were trying to play?

**Comment by arturhenryy** [comment] 2019-03-27 16:18
yeah i think you are right here. i just added them for info.
the piece i was trying to play was spring again, i checked the network tab and loading finished after 4m something and downloaded around 40mb. so if the play only starts when the fetching is done that might explain the delay. now clicking play with all the samples already in cache starts more or less instant.

**Comment by metalex9** [comment] 2019-03-27 16:42
Yeah something funky definitely happened there. I will test that one on a clean browser and see if it's reproducible or just a fluke.

**Comment by metalex9** [comment] 2019-04-01 02:06
Gonna close this as I can't reproduce. We can open it again if you have issues again.

**Closed by metalex9** 2019-04-01 02:06 UTC

**Comment by santosh898** [comment] 2020-01-25 02:41
`Uncaught TypeError: Failed to execute 'connect' on 'AudioNode': No function was found that 
  matched the signature provided.`

On clicking Play in Chrome 78 Linux. Working in firefox though.

**Comment by metalex9** [comment] 2020-01-25 19:33
@santosh898 I wasn't able to reproduce, but I just deployed a potential fix. Try again on 1.26.1 and let me know if that solved it for you.
